// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Database
{
    public partial class SwitchboardItems
    {
        public int SwitchboardId { get; set; }
        public short ItemNumber { get; set; }
        public string ItemText { get; set; }
        public short? Command { get; set; }
        public string Argument { get; set; }
    }
}