// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Database
{
    public partial class ВремяпроживанияResult
    {
        public int ID { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public string Отчетство { get; set; }
        public DateTime? Заселение { get; set; }
        public DateTime? Выселение { get; set; }
        [Column("Время проживания")]
        public int? Времяпроживания { get; set; }
    }
}
