// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Database
{
    public partial class Дежурства
    {
        public int Id { get; set; }
        public int? СтудентId { get; set; }
        public bool? Выполнено { get; set; }
        public DateTime? Дата { get; set; }

        public virtual Студенты Студент { get; set; }
    }
}