// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Database
{
    public partial class КоличествостудентоввкомнатеResult
    {
        [Column("Номер комнаты")]
        public int Номеркомнаты { get; set; }
        [Column("Количество студентов")]
        public int? Количествостудентов { get; set; }
    }
}
