// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Database
{
    public partial class Комнаты
    {
        public Комнаты()
        {
            Проживания = new HashSet<Проживания>();
        }

        public int НомерКомнаты { get; set; }
        public byte? КоличествоМест { get; set; }
        public int? ЭтажId { get; set; }

        public virtual Этажи Этаж { get; set; }
        public virtual ICollection<Проживания> Проживания { get; set; }
    }
}