// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Database
{
    public partial class КоличествоСтудентовПоКомнатам
    {
        public int НомерКомнаты { get; set; }
        public int? ЭтажId { get; set; }
        public int? CountСтудентId { get; set; }
    }
}