// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Database
{
    public partial class ПосещениегостямиResult
    {
        [Column("Имя посетителя")]
        public string Имяпосетителя { get; set; }
        [Column("Фамилия посетителя")]
        public string Фамилияпосетителя { get; set; }
        [Column("Отчество посетителя")]
        public string Отчествопосетителя { get; set; }
        [Column("Телефон посетителя")]
        public string Телефонпосетителя { get; set; }
        [Column("Дата посещения")]
        public DateTime? Датапосещения { get; set; }
    }
}
