// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Database
{
    public partial class Проживания
    {
        public int СтудентId { get; set; }
        public int? КомнатаId { get; set; }
        public DateTime? Заселение { get; set; }
        public DateTime? Выселение { get; set; }
        public decimal? ПлатаЗаМесяц { get; set; }
        public bool? Оплачено { get; set; }

        public virtual Комнаты Комнаты { get; set; }
        public virtual Студенты Студенты { get; set; }
    }
}