// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Database
{
    public partial class Студенты
    {
        public Студенты()
        {
            Гости = new HashSet<Гости>();
            Дежурства = new HashSet<Дежурства>();
        }

        public int СтудентId { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчетство { get; set; }
        public string НомерГруппы { get; set; }
        public int? Пол { get; set; }
        public string Льготы { get; set; }
        public string Телефон { get; set; }
        public string Паспорт { get; set; }

        public virtual Проживания Проживания { get; set; }
        public virtual ICollection<Гости> Гости { get; set; }
        public virtual ICollection<Дежурства> Дежурства { get; set; }
    }
}