// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Database
{
    public partial class Этажи
    {
        public Этажи()
        {
            Комнаты = new HashSet<Комнаты>();
        }

        public int ЭтажId { get; set; }
        public bool? НаличиеКухни { get; set; }
        public bool? НаличиеДуша { get; set; }

        public virtual ICollection<Комнаты> Комнаты { get; set; }
    }
}